const Pages = {
  conditions: [
    "blinded",
    "charmed",
    "deafened",
    "exhaustion",
    "frightened",
    "grappled",
    "incapacitated",
    "invisible",
    "paralyzed",
    "petrified",
    "poisoned",
    "prone",
    "restrained",
    "stunned",
    "unconscious",
  ],
  skills: [
    "acrobatics",
    "animal-handling",
    "arcana",
    "athletics",
    "deception",
    "history",
    "insight",
    "intimidation",
    "investigation",
    "medicine",
    "nature",
    "perception",
    "performance",
    "persuasion",
    "religion",
    "sleight-of-hand",
    "stealth",
    "survival",
  ],
  "ability-scores": ["cha", "con", "dex", "int", "str", "wis"],
  "damage-types": [
    "acid",
    "bludgeoning",
    "cold",
    "fire",
    "force",
    "lightning",
    "necrotic",
    "piercing",
    "poison",
    "psychic",
    "radiant",
    "slashing",
    "thunder",
  ],
  languages: [
    "abyssal",
    "celestial",
    "common",
    "deep-speech",
    "draconic",
    "dwarvish",
    "elvish",
    "giant",
    "gnomish",
    "goblin",
    "halfling",
    "infernal",
    "orc",
    "primordial",
    "sylvan",
    "undercommon",
  ],
  "starting-equipment": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  traits: [
    "artificers-lore",
    "brave",
    "breath-weapon",
    "damage-resistance",
    "darkvision",
    "draconic-ancestry",
    "dwarven-combat-training",
    "dwarven-resilience",
    "dwarven-toughness",
    "elf-weapon-training",
    "extra-language",
    "fey-ancestry",
    "gnome-cunning",
    "halfling-nimbleness",
    "hellish-resistance",
    "high-elf-cantrip",
    "infernal-legacy",
    "keen-senses",
    "lucky",
    "menacing",
    "naturally-stealthy",
    "relentless-endurance",
    "savage-attacks",
    "skill-versatility",
    "stonecunning",
    "tinker",
    "trance",
  ],
  races: [
    "dragonborn",
    "dwarf",
    "elf",
    "gnome",
    "half-elf",
    "half-orc",
    "halfling",
    "human",
    "tiefling",
  ],
};

export default Pages;
